name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyshark psutil ctypes-win32

    - name: Add Tesseract to PATH (Workaround)
      run: |
        Add-Content $env:GITHUB_PATH "C:\Program Files\Wireshark"

    - name: Build executable
      run: |
        pyinstaller --onefile `
          --add-data="rtmp_auto.log;." `
          --icon=icon.ico `
          --name RTMPAutoTool `
          --noconsole `
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: RTMPAutoTool
        path: dist/RTMPAutoTool.exe
