name: Auto Build and Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write  # 必须的发布权限

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create required files
      run: |
        # 创建日志文件
        if (-not (Test-Path rtmp_auto.log)) {
          New-Item rtmp_auto.log -ItemType File
        }

    - name: Verify environment
      run: |
        # 确认关键文件存在
        if (-not (Test-Path dy_PushFlow.py)) { 
          Write-Error "主脚本缺失!"
          exit 1 
        }

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyshark psutil

    - name: Configure Wireshark
      run: |
        # 验证Wireshark安装
        $tsharkPath = "${env:ProgramFiles}\Wireshark\tshark.exe"
        if (-not (Test-Path $tsharkPath)) {
            Write-Error "❌ Wireshark未安装: $tsharkPath"
            exit 1
        }
        # 添加到PATH
        Add-Content $env:GITHUB_PATH "${env:ProgramFiles}\Wireshark"

    - name: Build executable
      run: |
        pyinstaller --onefile `
          --add-binary "${env:ProgramFiles}\Wireshark\tshark.exe;." `
          --add-data "rtmp_auto.log;." `
          --name DouyinPushTool `
          --noconsole `
          dy_PushFlow.py

    - name: Publish Release
      uses: softprops/action-gh-release@v2
      if: success()
      with:
        files: |
          dist/DouyinPushTool.exe
        tag_name: build-${{ github.run_number }}
        name: "Release ${{ github.run_number }}"
        body: |
          自动构建信息：
          - 提交ID: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          - 构建时间: ${{ steps.date.outputs.current_date }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
