name: Auto Build and Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create required files
      run: |
        # 自动创建必要的空文件
        if (-not (Test-Path rtmp_auto.log)) {
          New-Item rtmp_auto.log -ItemType File
        }

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyshark psutil

    - name: Add Wireshark to PATH
      run: |
        Add-Content $env:GITHUB_PATH "C:\Program Files\Wireshark"

    - name: Build executable
      run: |
        pyinstaller --onefile `
          --add-data="rtmp_auto.log;." `
          --name DouyinPushTool `
          --noconsole `
          dy_PushFlow.py

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        files: |
          dist/DouyinPushTool.exe
        tag_name: auto-build-${{ github.run_id }}   # 自动生成唯一标签
        name: "自动构建版本 (${{ github.sha }})"
        body: |
          自动生成的构建版本
          提交ID: ${{ github.sha }}
          构建时间: ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
