name: Build EXE

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # 安装UPX压缩工具
        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-win64.zip" -OutFile upx.zip
        Expand-Archive upx.zip -DestinationPath upx
        echo "${{ github.workspace }}\upx\upx-4.0.2-win64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build EXE
      run: |
        pyinstaller build.spec
        Compress-Archive -Path dist/* -DestinationPath RTMPHunter.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RTMPHunter
        path: |
          dist/RTMPHunter.exe
          RTMPHunter.zip
