name: Build Validation

on:
  push:
    tags:
      - 'v[0-9]+.*'  # 匹配v开头+数字的标签
    branches: [main]
  workflow_dispatch:

jobs:
  debug-build:
    runs-on: windows-latest
    timeout-minutes: 25

    steps:
    - name: Show Tag Info
      run: |
        echo "触发标签: ${{ github.ref }}"
        git log -1  # 显示提交信息

    - name: Validate Files
      run: |
        ls -Recurse  # 显示完整目录结构
        if (-not (Test-Path build.spec)) { exit 1 }

    - name: Build EXE
      run: pyinstaller --clean --noconfirm build.spec

    - name: Verify Artifacts
      run: |
        if (-not (Test-Path dist/RTMPAuto.exe)) {
          Write-Error "EXE文件未生成!"
          exit 1
        }
