name: Build Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller psutil pyshark

    - name: Build EXE
      run: |
        pyinstaller --noconfirm build.spec
        Compress-Archive -Path dist/* -DestinationPath RTMPAuto.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: RTMPAuto
        path: |
          dist/
          RTMPAuto.zip
